In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [2]:
df.shape

(10000, 14)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [6]:
df["Geography"].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [7]:
df["Gender"].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [8]:
# dropping irrelevant columns implementing feature selection

df.drop(columns = ['RowNumber','CustomerId','Surname'],inplace=True)

In [9]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [10]:
df.shape

(10000, 11)

# one hot encoding for categorical variables

In [11]:
df = pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False

In [12]:
df.shape

(10000, 12)

# Train test split and scaling

In [13]:
X = df.drop(columns=['Exited'])
y = df['Exited'].values

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_trf = scaler.fit_transform(X_train)
X_test_trf = scaler.transform(X_test)

In [15]:
X_test_trf.shape

(2000, 11)

# Building the network using tensorflow

In [16]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential 
from tensorflow.keras.layers import Dense

In [17]:
def create_model():
    model = Sequential([
        Dense(11, activation='relu', input_shape=(X_train_trf.shape[1],)),
        Dense(11, activation='relu'),
        Dense(1, activation='sigmoid')
    ])

    model.compile(
        optimizer='sgd',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

# Implementing Batch Gradient

In [18]:
model_batch = create_model()

model_batch.fit(
    X_train_trf,
    y_train,
    batch_size=len(X_train_trf),
    epochs=30,
    verbose=1,
    validation_split=0.2)

C:\Users\Shekhar Kumar\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.2195 - loss: 1.0063 - val_accuracy: 0.2094 - val_loss: 0.9902
Epoch 2/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 405ms/step - accuracy: 0.2219 - loss: 0.9938 - val_accuracy: 0.2125 - val_loss: 0.9783
Epoch 3/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 403ms/step - accuracy: 0.2242 - loss: 0.9818 - val_accuracy: 0.2138 - val_loss: 0.9668
Epoch 4/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 427ms/step - accuracy: 0.2272 - loss: 0.9702 - val_accuracy: 0.2163 - val_loss: 0.9556
Epoch 5/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 283ms/step - accuracy: 0.2291 - loss: 0.9589 - val_accuracy: 0.2206 - val_loss: 0.9449
Epoch 6/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 293ms/step - accuracy: 0.2328 - loss: 0.9480 - val_accuracy: 0.2244 - val_loss: 0.9344
Epoch 7/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 217ms/step - accuracy: 0.2381 - loss: 0.9375 - val_accuracy: 0.2300 - val_loss: 0.9243
Epoch 8/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 205ms/step - accuracy: 0.2427 - loss: 0.9272 - val_accuracy: 0.2313 - val_loss: 0.9145
Epoch 9/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 228ms/step - accuracy: 0.2461 - loss: 0.9173 - val_accuracy: 0.2375 - val_loss: 0.9050
Epoch 10/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 229ms/step - accuracy: 0.2491 - loss: 0.9077 - val_accuracy: 0.2425 - val_loss: 0.8957
Epoch 11/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 222ms/step - accuracy: 0.2530 - loss: 0.8984 - val_accuracy: 0.2425 - val_loss: 0.8868
Epoch 12/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 217ms/step - accuracy: 0.2572 - loss: 0.8894 - val_accuracy: 0.2494 - val_loss: 0.8782
Epoch 13/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 410ms/step - accuracy: 0.2616 - loss: 0.8806 - val_accuracy: 0.2562 - val_loss: 0.8697
Epoch 14/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 227ms/step - accuracy: 0.2650 - loss: 0.8721 - val_accuracy: 0.2600 - val_loss: 0.8616
Epoch 15/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 225ms/step - accuracy: 0.2722 - loss: 0.8638 - val_accuracy: 0.2719 - val_loss: 0.8537
Epoch 16/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 221ms/step - accuracy: 0.2780 - loss: 0.8558 - val_accuracy: 0.2788 - val_loss: 0.8460
Epoch 17/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step - accuracy: 0.2836 - loss: 0.8480 - val_accuracy: 0.2887 - val_loss: 0.8385
Epoch 18/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 211ms/step - accuracy: 0.2889 - loss: 0.8405 - val_accuracy: 0.2956 - val_loss: 0.8313
Epoch 19/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 213ms/step - accuracy: 0.2953 - loss: 0.8331 - val_accuracy: 0.2975 - val_loss: 0.8243
Epoch 20/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 206ms/step - accuracy: 0.3025 - loss: 0.8260 - val_accuracy: 0.3081 - val_loss: 0.8174
Epoch 21/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 317ms/step - accuracy: 0.3095 - loss: 0.8191 - val_accuracy: 0.3131 - val_loss: 0.8108
Epoch 22/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 242ms/step - accuracy: 0.3211 - loss: 0.8124 - val_accuracy: 0.3212 - val_loss: 0.8043
Epoch 23/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 218ms/step - accuracy: 0.3291 - loss: 0.8058 - val_accuracy: 0.3294 - val_loss: 0.7980
Epoch 24/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 234ms/step - accuracy: 0.3378 - loss: 0.7995 - val_accuracy: 0.3325 - val_loss: 0.7919
Epoch 25/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 213ms/step - accuracy: 0.3470 - loss: 0.7933 - val_accuracy: 0.3413 - val_loss: 0.7860
Epoch 26/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 224ms/step - accuracy: 0.3566 - loss: 0.7873 - val_accuracy: 0.3475 - val_loss: 0.7802
Epoch 27/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step - accuracy: 0.3670 - loss: 0.7814 - val_accuracy: 0.3600 - val_loss: 0.7746
Epoch 28/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 214ms/step - accuracy: 0.3741 - loss: 0.7757 - val_accuracy: 0.3650 - val_loss: 0.7691
Epoch 29/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 227ms/step - accuracy: 0.3841 - loss: 0.7702 - val_accuracy: 0.3775 - val_loss: 0.7638
Epoch 30/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 215ms/step - accuracy: 0.3925 - loss: 0.7648 - val_accuracy: 0.3875 - val_loss: 0.7586

In [20]:
model_batch.layers[0].get_weights()

[array([[ 2.1069331e-01, -1.8672849e-01, -3.5502365e-01, -3.4112304e-01,
         -2.2234779e-04,  5.1296633e-01, -4.8539788e-01,  1.0405661e-01,
         -9.2090063e-02, -4.6049720e-03,  3.8777828e-01],
        [ 1.7698398e-01, -4.5271537e-01,  2.1115442e-01,  4.3393049e-01,
          4.3102229e-01,  2.9875976e-01,  4.2616244e-02,  2.8807458e-01,
         -6.1113100e-02,  1.0347843e-01,  4.3630654e-01],
        [ 3.0462611e-01,  1.2105254e-02, -1.4115289e-01,  2.9405200e-01,
          2.7417615e-01, -3.0207375e-01,  5.2220243e-01, -1.2555771e-01,
         -5.1211417e-01,  2.7594054e-01,  6.0312271e-02],
        [ 3.3516252e-01,  3.7648544e-01, -9.5779426e-02,  5.8014430e-03,
          2.3935129e-01, -4.6063063e-01,  3.0646333e-01,  3.5360372e-01,
          4.5158118e-01,  3.6640719e-01, -4.0715179e-01],
        [ 4.4935659e-01, -5.0904029e-03, -3.1300831e-01,  1.9504376e-01,
         -3.0708876e-01,  1.6184294e-01, -3.2438979e-01, -5.1745588e-01,
          9.6763648e-02, -4.5909381e-01,  2.3294650e-01],
        [ 1.7518125e-02, -2.7372572e-01,  5.3590365e-02,  2.9833239e-01,
          2.0771132e-01,  5.1652241e-01,  1.1789682e-01,  3.4597423e-02,
         -4.8858738e-01, -2.8703475e-01, -4.3103334e-01],
        [-1.7150746e-01,  4.6086392e-01,  3.1152046e-01, -3.3665240e-01,
         -2.6990515e-01,  3.1652099e-01, -3.4513852e-01, -1.3952167e-01,
          1.7412239e-01,  4.6610367e-01, -3.7452924e-01],
        [-7.0069595e-03,  1.6560121e-01,  4.6391964e-01, -4.5547459e-02,
         -1.1786563e-01,  5.0134689e-01,  1.2771834e-02, -4.3700844e-01,
          4.9736750e-01, -1.5738499e-01,  3.6162218e-01],
        [-1.3530290e-01, -2.5045216e-01,  3.7317905e-01, -1.2855349e-01,
         -2.8779411e-01,  2.7078670e-01, -3.3889347e-01, -4.9265146e-01,
          1.4234567e-01,  2.6787183e-01,  4.6753362e-01],
        [-1.7895563e-01,  3.5372156e-01,  5.4591466e-02,  5.3860445e-02,
          4.7573015e-01, -7.6924115e-02,  2.6052600e-01, -3.8809612e-01,
         -3.6086971e-01,  2.0348959e-01, -2.8604606e-01],
        [ 2.1648493e-01,  1.4659530e-01,  2.4658686e-01,  4.8593688e-01,
          3.3673027e-01, -3.7906852e-01, -3.2772249e-01, -2.0575306e-01,
         -5.1936591e-01, -6.4119652e-02, -1.2378732e-02]], dtype=float32),
 array([-0.00985633, -0.02044283, -0.0385632 , -0.00239486,  0.00166495,
        -0.00638511, -0.00211478, -0.00302893, -0.00052547,  0.00886016,
         0.00514565], dtype=float32)]

In [21]:
model_batch.layers[1].get_weights()

[array([[ 0.32228237, -0.1652873 ,  0.2750088 , -0.40126818,  0.42663187,
          0.01256921, -0.1825046 ,  0.19744237,  0.14154111, -0.41227812,
          0.4946485 ],
        [ 0.22645591,  0.29408923,  0.03971896,  0.18028203, -0.24321105,
          0.45736134, -0.35216463,  0.48566347, -0.14967772,  0.06355688,
          0.26077506],
        [ 0.20047675,  0.37536603,  0.3298467 , -0.34771413, -0.50666547,
         -0.4506632 ,  0.03999875,  0.00824638, -0.18969508,  0.47717693,
          0.4211952 ],
        [ 0.02709517,  0.14768255,  0.3628322 , -0.46064913,  0.20220108,
          0.12765239, -0.49281263,  0.15473567, -0.25646135, -0.16276227,
          0.20875624],
        [ 0.2865621 , -0.43981642, -0.17125413, -0.24400608, -0.11828103,
          0.16029753,  0.2602117 , -0.32969508,  0.4715825 ,  0.44325018,
         -0.49438822],
        [ 0.4533715 , -0.5103277 ,  0.3876569 , -0.31308612,  0.44956297,
         -0.30374992,  0.06501246, -0.15967849, -0.5068158 , -0.12137439,
          0.36529213],
        [ 0.07863849,  0.04187619,  0.26183468, -0.3866226 , -0.16252615,
          0.259236  , -0.25385866,  0.3186667 , -0.11639263, -0.05002425,
         -0.294407  ],
        [ 0.0077229 ,  0.23144697,  0.5200092 ,  0.46396822, -0.4667313 ,
          0.03082163,  0.4908284 ,  0.2602542 ,  0.02048383,  0.49183744,
          0.08294178],
        [-0.4258524 ,  0.36650532,  0.17620197,  0.20181412,  0.49760902,
         -0.36094138, -0.2648591 ,  0.14785701, -0.03076019,  0.07506528,
          0.4104423 ],
        [-0.00972098, -0.41657528, -0.41573662,  0.37409323, -0.00436018,
          0.50472456, -0.06565382, -0.18441235, -0.26167908, -0.00948323,
          0.32540512],
        [-0.20805074,  0.09707924,  0.31268755,  0.17865275,  0.44217286,
          0.02644467,  0.30219737,  0.1370346 , -0.21935084,  0.11824578,
          0.43130845]], dtype=float32),
 array([-0.04285514, -0.00805771,  0.01313615,  0.0215168 ,  0.03086229,
         0.02777223,  0.01009061, -0.0323015 , -0.00029548, -0.02195238,
        -0.04012955], dtype=float32)]

In [22]:
model_batch.layers[2].get_weights()

[array([[ 0.4974874 ],
        [ 0.13513137],
        [-0.17304677],
        [-0.6264248 ],
        [-0.57222426],
        [-0.48963982],
        [-0.35622704],
        [ 0.3577406 ],
        [ 0.02275775],
        [ 0.25903907],
        [ 0.41008717]], dtype=float32),
 array([-0.10200968], dtype=float32)]

In [19]:
y_log = model_batch.predict(X_test_trf)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

In [20]:
y_pred = np.where(y_log > 0.5 , 1 , 0)
from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_pred)

0.38

# Implementing Stochastic Gradient Descent

In [21]:
model_sgd = create_model()

model_sgd.fit(
    X_train_trf,
    y_train,
    batch_size=1,
    epochs=3,
    verbose=1,
    validation_split=0.2)

# model_sgd.layers[0].get_weights()

C:\Users\Shekhar Kumar\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/3
6400/6400 ━━━━━━━━━━━━━━━━━━━━ 34s 5ms/step - accuracy: 0.8097 - loss: 0.4461 - val_accuracy: 0.8244 - val_loss: 0.4199
Epoch 2/3
6400/6400 ━━━━━━━━━━━━━━━━━━━━ 32s 5ms/step - accuracy: 0.8258 - loss: 0.4054 - val_accuracy: 0.8194 - val_loss: 0.4059
Epoch 3/3
6400/6400 ━━━━━━━━━━━━━━━━━━━━ 32s 5ms/step - accuracy: 0.8325 - loss: 0.3882 - val_accuracy: 0.8331 - val_loss: 0.3862

In [26]:
model_sgd.layers[1].get_weights()

[array([[-0.14080068, -0.2289193 , -0.11922805,  0.6014932 ,  0.44573563,
         -0.1151396 ,  0.02609706,  0.16900311,  0.25718167,  0.16138741,
          0.3102988 ],
        [-0.45356947, -0.39366162, -0.15624085, -0.2937329 , -0.07287353,
         -0.55494744, -0.0897253 , -0.12600023,  0.3203888 ,  0.09847242,
         -0.424586  ],
        [ 0.12826721,  0.11916425, -0.4631147 ,  0.50481284, -0.06238472,
         -0.16516836,  0.07449918,  0.2028376 ,  0.11753605,  0.15159373,
          0.36838454],
        [ 0.13883437, -0.24482827, -0.31957006, -0.6609127 , -0.21678893,
          0.24990204, -0.21998173, -0.0554263 ,  0.0426238 , -0.08565238,
         -0.07021891],
        [ 0.11103641, -0.43228257,  0.45197332, -0.02417003, -0.41612855,
          0.3670926 , -0.22511709, -0.11193589, -0.23182008,  0.4300746 ,
         -0.12032007],
        [ 0.16995603, -0.11402183, -0.14603418, -0.0647153 , -0.10811961,
         -0.37945327, -0.10293589,  0.10917562, -0.46566218, -0.19521938,
          0.37551185],
        [ 0.17751145, -0.06147126,  0.519988  , -0.1105523 , -0.49371472,
          0.13272901,  0.50886536, -0.27423573,  0.03362132,  0.48486435,
          0.4679046 ],
        [ 1.0886004 , -0.18550324, -0.11974994, -0.3910978 , -0.3685683 ,
          0.5190428 , -0.2421696 , -0.18852666, -0.49068883, -0.24586244,
         -0.31809077],
        [-0.3908523 , -0.21624617, -0.04176937, -0.23772663, -0.06447981,
         -0.28645638,  0.49128288, -0.22711405,  0.16666427, -0.05614545,
         -0.22871175],
        [-0.36244324,  0.6740368 , -0.45870322, -0.0067431 , -0.20693737,
          0.14560334, -0.33159772,  0.6670096 ,  0.25617585, -0.40700763,
         -0.22093627],
        [-0.63841456,  0.13565163,  0.12519473, -0.38139704, -0.0941633 ,
         -0.2348489 ,  0.7062788 , -0.23742583,  0.26085195, -0.48728645,
         -0.35595363]], dtype=float32),
 array([-2.1983357e-01, -1.3010831e-01,  3.6107218e-01,  2.4582544e-01,
         8.4348761e-02, -3.1832118e-02,  6.7760015e-01,  2.2269855e-04,
        -1.3276505e-01,  1.8614708e-01,  5.1540577e-01], dtype=float32)]

In [27]:
model_sgd.layers[2].get_weights()

[array([[ 1.0254037 ],
        [ 0.45685083],
        [-0.35834724],
        [-0.83428895],
        [-0.61272275],
        [ 0.4688326 ],
        [-0.73344487],
        [ 0.51297456],
        [ 0.36986026],
        [-0.3412611 ],
        [-0.652944  ]], dtype=float32),
 array([-0.71250427], dtype=float32)]

In [28]:
y_log = model_sgd.predict(X_test_trf)
y_pred = np.where(y_log > 0.5 , 1 , 0)
accuracy_score(y_test , y_pred)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

0.85

# Implementing Mini Batch GD

In [23]:
model_mini = create_model()

model_mini.fit(
    X_train_trf,
    y_train,
    batch_size=64,
    epochs=30,
    verbose=1,
    validation_split=0.2)

Epoch 1/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.7034 - loss: 0.6191 - val_accuracy: 0.7969 - val_loss: 0.5530
Epoch 2/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7953 - loss: 0.5186 - val_accuracy: 0.7969 - val_loss: 0.5071
Epoch 3/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7952 - loss: 0.4887 - val_accuracy: 0.7944 - val_loss: 0.4838
Epoch 4/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.7977 - loss: 0.4717 - val_accuracy: 0.7994 - val_loss: 0.4696
Epoch 5/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8017 - loss: 0.4608 - val_accuracy: 0.7956 - val_loss: 0.4605
Epoch 6/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8053 - loss: 0.4531 - val_accuracy: 0.8012 - val_loss: 0.4543
Epoch 7/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8075 - loss: 0.4473 - val_accuracy: 0.8037 - val_loss: 0.4498
Epoch 8/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8109 - loss: 0.4425 - val_accuracy: 0.8100 - val_loss: 0.4464
Epoch 9/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8117 - loss: 0.4388 - val_accuracy: 0.8094 - val_loss: 0.4438
Epoch 10/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8138 - loss: 0.4354 - val_accuracy: 0.8144 - val_loss: 0.4413
Epoch 11/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8153 - loss: 0.4325 - val_accuracy: 0.8131 - val_loss: 0.4394
Epoch 12/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8148 - loss: 0.4299 - val_accuracy: 0.8150 - val_loss: 0.4376
Epoch 13/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8159 - loss: 0.4274 - val_accuracy: 0.8156 - val_loss: 0.4358
Epoch 14/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8166 - loss: 0.4251 - val_accuracy: 0.8181 - val_loss: 0.4342
Epoch 15/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8191 - loss: 0.4227 - val_accuracy: 0.8175 - val_loss: 0.4326
Epoch 16/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8202 - loss: 0.4204 - val_accuracy: 0.8144 - val_loss: 0.4309
Epoch 17/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8220 - loss: 0.4181 - val_accuracy: 0.8188 - val_loss: 0.4292
Epoch 18/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8242 - loss: 0.4158 - val_accuracy: 0.8200 - val_loss: 0.4274
Epoch 19/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8256 - loss: 0.4134 - val_accuracy: 0.8213 - val_loss: 0.4256
Epoch 20/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8263 - loss: 0.4110 - val_accuracy: 0.8213 - val_loss: 0.4236
Epoch 21/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8284 - loss: 0.4084 - val_accuracy: 0.8213 - val_loss: 0.4214
Epoch 22/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8311 - loss: 0.4056 - val_accuracy: 0.8219 - val_loss: 0.4192
Epoch 23/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8336 - loss: 0.4026 - val_accuracy: 0.8231 - val_loss: 0.4165
Epoch 24/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8334 - loss: 0.3998 - val_accuracy: 0.8288 - val_loss: 0.4140
Epoch 25/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8361 - loss: 0.3966 - val_accuracy: 0.8288 - val_loss: 0.4112
Epoch 26/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8383 - loss: 0.3934 - val_accuracy: 0.8288 - val_loss: 0.4085
Epoch 27/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8394 - loss: 0.3902 - val_accuracy: 0.8300 - val_loss: 0.4057
Epoch 28/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8428 - loss: 0.3869 - val_accuracy: 0.8294 - val_loss: 0.4028
Epoch 29/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8441 - loss: 0.3838 - val_accuracy: 0.8288 - val_loss: 0.4000
Epoch 30/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8459 - loss: 0.3806 - val_accuracy: 0.8325 - val_loss: 0.3971

In [30]:
y_log = model_mini.predict(X_test_trf)
y_pred = np.where(y_log > 0.5 , 1 , 0)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [31]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_pred)

0.799